export default [
  {
    slug: 'spa-framework',
    title: 'SPA 프레임워크',
    parents: [],
    children: ['react', 'vue', 'svelte'],
    content: '',
  },
  {
    slug: 'vue',
    title: '뷰',
    parents: ['spa-framework'],
    children: [],
    content: '',
  },
  {
    slug: 'svelte',
    title: '스벨트',
    parents: ['spa-framework'],
    children: [],
    content: '',
  },
  {
    slug: 'react',
    title: '리액트',
    parents: ['spa-framework'],
    children: ['remix', 'next-js'],
    content: '> "React is a JavaScript library for building user interfaces" - [리액트 공식 문서](https://beta.reactjs.org/learn/thinking-in-react)',
  },
  {

    slug: 'state-management',
    title: '프런트엔드 상태 관리',
    parents: [],
    children: ['redux'],
    content: '반응형(reactive) 상태를 관리하는 라이브러리들이 있습니다. 이런 라이브러리들은 보통 내부적으로는 구독(subscribe)이나, 관찰자(observer) 패턴을 이용해서, 상태가 변하면 부수효과를 프런트엔드 프레임워크에게 전파해줍니다. react에서는 redux, recoil, jotai 등이 있고, vue에서는 pinia가 공식입니다.',
  },
  {
    slug: 'redux',
    title: '리덕스',
    parents: ['state-management'],
    children: [],
    content: '리덕스는 프레임워크에 무관한 프런트엔드 상태 관리 라이브러리입니다. 하지만 리액트 생태계에서 가장 널리 쓰여왔기 때문에, 리액트를 쓰는 회사에서 요구하는 경우가 많습니다.',
  },
  {
    slug: 'web-standard',
    title: '웹 표준',
    parents: [],
    children: ['html', 'css', 'javascript'],
    content: '',
  },
  {
    slug: 'html',
    title: 'HTML: 하이퍼 텍스트 마크업 언어',
    parents: ['web-standard'],
    children: ['semantic-html'],
    content: '',
  },
  {
    slug: 'semantic-html',
    title: '시맨틱 HTML',
    parents: ['html'],
    children: [],
    content: '',
  },
  {
    slug: 'css',
    title: 'CSS 캐스케이딩 스타일 시트',
    parents: ['web-standard'],
    children: ['sass'],
    content: `> WHAT IS CSS? Cascading Style Sheets (CSS) is a simple mechanism for adding style (e.g., fonts, colors, spacing) to Web documents. \n>\n> 출처: <a rel="author" class="link link-primary" href="https://www.w3.org/Style/CSS">W3C Cascading Style Sheets home page</a>`,
  },
  {
    slug: 'javascript',
    title: '자바스크립트',
    parents: ['web-standard'],
    children: ['typescript'],
    content: '',
  },
  {
    slug: 'typescript',
    title: '타입스크립트',
    parents: ['javascript'],
    children: [],
    content: '',
  },
  {
    slug: 'sass',
    title: 'SASS',
    parents: ['css'],
    children: [],
    content: '',
  },
  {
    slug: 'ssr',
    title: 'SSR',
    parents: [],
    children: ['remix', 'next-js'],
    content: '',
  },
  {
    slug: 'web-api',
    title: '웹 API',
    parents: [],
    children: ['restful-api', 'graph-ql', 'grpc'],
    content: '',
  },
  {
    slug: 'restful-api',
    title: 'RESTful API',
    parents: ['web-api'],
    children: [],
    content: 'RESTful API는 HTTP를 가지고 서버와 상태 데이터를 주고 받는 표준입니다. 과거에 Ajax라 부르던 것과도 비슷한 의미로 쓰입니다. REST는 엄격한 정의가 있고 논문도 있지만, 이를 잘 이해하고 사용하는 경우는 거의 없습니다. 보통 RESTful API라 하면 HTTP API를 이야기합니다.\n\n채용공고에서 RESTful API를 언급하는 빈도는 점점 줄어들고 있습니다. 그 이유는 RESTful를 사용하지 않기 때문이라기 보다는, 너무나 당연해졌기 때문이라 생각합니다.',
  },
  {
    slug: 'git',
    title: '깃',
    parents: [],
    children: ['github'],
    content: '',
  },
  {
    slug: 'github',
    title: '깃허브',
    parents: ['git'],
    children: [],
    content: '',
  },
  {
    slug: 'remix',
    title: '리믹스',
    parents: ['react', 'ssr'],
    children: [],
    content: '',
  },
  {
    slug: 'next-js',
    title: '넥스트js',
    parents: ['react', 'ssr'],
    children: [],
    content: '',
  },
  {
    slug: 'test',
    title: '테스트',
    parents: [],
    children: ['tdd'],
    content: '',
  },
  {
    slug: 'tdd',
    title: '테스트 주도 개발',
    parents: [],
    children: ['tdd'],
    content: '',
  },
  {
    slug: 'cloud',
    title: '클라우드',
    parents: [],
    children: ['aws'],
    content: '',
  },
  {
    slug: 'aws',
    title: '아마존 웹 서비스',
    parents: ['cloud'],
    children: ['aws-rds'],
    content: '',
  },
  {
    slug: 'aws-rds',
    title: 'AWS RDS',
    parents: ['aws', 'rdbms'],
    children: [],
    content: '',
  },
  {
    slug: 'english',
    title: '영어',
    parents: [],
    children: [],
    content: '',
  },
  {
    slug: 'database',
    title: '데이터베이스',
    parents: [],
    children: ['relational-db', 'no-sql-db'],
    content: '',
  },
  {
    slug: 'rdbms',
    title: '관계형 데이터베이스',
    parents: ['database'],
    children: ['sqlite', 'mysql', 'postgresql'],
    content: '',
  },
  {
    slug: 'sqlite',
    title: 'SQLite',
    parents: ['relational-db'],
    children: [],
    content: '',
  },
  {
    slug: 'mysql',
    title: 'MySQL, MariaDB',
    parents: ['relational-db'],
    children: [],
    content: '',
  },
  {
    slug: 'postgresql',
    title: 'PostgreSQL',
    parents: ['relational-db'],
    children: [],
    content: '',
  },
  {
    slug: 'no-sql-db',
    title: 'NoSQL 데이터베이스',
    parents: ['database'],
    children: ['key-value-db', 'document-db', 'search-db', 'graph-db'],
    content: '',
  },
  {
    slug: 'key-value-db',
    title: '키-값 데이터베이스',
    parents: ['no-sql-db'],
    children: ['redis', 'dynamodb', 'dragonfly'],
    content: '',
  },
  {
    slug: 'redis',
    title: '레디스',
    parents: ['key-value-db'],
    children: [],
    content: '',
  },
  {
    slug: 'dynamodb',
    title: 'DynamoDB',
    parents: ['key-value-db', 'document-db'],
    children: [],
    content: '',
  },
  {
    slug: 'dragonfly',
    title: '드래곤플라이',
    parents: ['key-value-db'],
    children: [],
    content: '',
  },
  {
    slug: 'document-db',
    title: '문서 데이터베이스',
    parents: ['no-sql-db'],
    children: ['mongodb', 'dynamodb'],
    content: '',
  },
  {
    slug: 'mongodb',
    title: '몽고 DB',
    parents: ['document-db'],
    children: [],
    content: '',
  },
  {
    slug: 'search-db',
    title: '검색 데이터베이스',
    parents: ['no-sql-db'],
    children: [],
    content: '',
  },
  {
    slug: 'graph-db',
    title: '그래프 데이터베이스',
    parents: ['no-sql-db'],
    children: [],
    content: '',
  },
  {
    slug: 'pr-lang',
    title: '프로그래밍 언어',
    parents: [],
    children: ['javascript', 'java', 'python', 'go', 'rust', 'ruby', 'c', 'c#', 'php'],
    content: '',
  },
  {
    slug: 'java',
    title: '자바',
    parents: ['pr-lang'],
    children: ['kotlin', 'scala', 'clojure'],
    content: '',
  },
  {
    slug: 'kotlin',
    title: '코틀린',
    parents: ['java'],
    children: [],
    content: '',
  },
  {
    slug: 'scala',
    title: '스칼라',
    parents: ['java'],
    children: [],
    content: '',
  },
  {
    slug: 'clojure',
    title: '클로저',
    parents: ['java'],
    children: [],
    content: '',
  },
  {
    slug: 'javascript',
    title: '자바스크립트',
    parents: ['pr-lang'],
    children: ['typescript', 'rescript', 'js-runtime'],
    content: '',
  },
  {
    slug: 'wasm',
    title: '웹 어셈블리',
    parents: ['javascript'],
    children: ['rust'],
    content: '',
  },
  {
    slug: 'typescript',
    title: '타입스크립트',
    parents: ['javascript'],
    children: [],
    content: '',
  },
  {
    slug: 'rescript',
    title: '리스크립트',
    parents: ['javascript'],
    children: [],
    content: '',
  },
  {
    slug: 'js-runtime',
    title: 'js 런타임',
    parents: ['javascript'],
    children: ['nodejs', 'deno'],
    content: '',
  },
  {
    slug: 'nodejs',
    title: '노드js',
    parents: ['js-runtime'],
    children: [],
    content: '',
  },
  {
    slug: 'deno',
    title: '디노',
    parents: ['js-runtime'],
    children: [],
    content: '',
  },
]